created stdizer function - more testing required
UBC-MDS/prepackPy pull request #16
Opened 2019-02-12 05:24 UTC by smwatts

2019-02-12 06:20 UTC, jchen9314 commented
To create the Value/Type Error exceptions in function:
try the following code:
```
if not isinstance(X, (pd.DataFrame, np.ndarray)):
     raise TypeError(error messsage)
```
Hope it would help you.

2019-02-12 19:43 UTC, jchen9314 commented
For running the testing script, I just use `pytest test_file_name` in the command line and see if all test cases pass.

2019-02-12 20:09 UTC, smwatts commented
Thanks JY!

2019-02-12 23:00 UTC, jchen9314 requested changes
Good job! Few comments on test_stdizer.py.

2019-02-12 23:00 UTC, jchen9314 commented on tests/test_stdizer.py
> +    with pytest.raises(ValueError):
1. There are duplicated code in line 59 and 60. 
2. Did you use `data_2` and `np_data_2` in this test case?
3. To convert the data type, we could use `np.array()`.

2019-02-13 00:08 UTC, smwatts commented on tests/test_stdizer.py
> +    with pytest.raises(ValueError):
fixed! good catch thanks

2019-02-13 00:10 UTC, jchen9314 approved these changes

2019-02-13 00:18 UTC, apchiodo approved these changes

2019-02-13 00:30 UTC, merged